# code: language=Ansible insertSpaces=true tabSize=2

- hosts: nios
  connection: local
  collections:
    - infoblox.nios_modules
  tasks:

    - name: Assert arguments
      assert:
        that:
          - item.data | length > 0
        fail_msg: "Rejected requested {{ item.kind }}: '{{ item.data }}'"
        success_msg: "Accepted requested {{ item.kind }}: '{{ item.data }}'"
      with_items:
        - kind: "network view"
          data: "{{ request_view | default('BOPI-test') }}"
        - kind: "network"
          data: "{{ request_network | default('') }}"
        - kind: "requestor"
          data: "{{ request_requestor | default('') }}"
      tags: [always]

    - name: Assert network view
      assert:
        that:
          - item.data == "BOPI-test"
        fail_msg: "Not allowed to use this netrwork view."
        success_msg: "Network view BOPI-test"
      with_items:
        - kind: "network view"
          data: "{{ request_view | default('BOPI-test') }}"
      tags: [always]
    
    - name: Debug
      debug:
        var: nios_provider
      tags: [always]

    - name: Lookup view, container and network
      set_fact:
        infoblox_view: "{{ lookup('community.general.nios', 'view', filter={'name': request_view}, provider=nios_provider) }}"
        infoblox_network: "{{ lookup('community.general.nios', 'network', filter={'network': request_network}, provider=nios_provider) }}"
      tags: [always]

    - name: Assert network does not already exists
      assert:
        that:
          - infoblox_network | length == 0
        success_msg: "The request network does not exists, continue"
        fail_msg: "The request network {{ request_network }} already exists"
      tags: [always]

    - name: Generate attributes
      set_fact:
        request_comment: "{{ request_comment | default('') }}"
        request_description: "{{ request_description | default('Added by BOPI') }}"
      tags: [always]

    - name: Create network
      infoblox.nios_modules.nios_network:
        network: "{{ request_network }}"
        network_view: "{{ request_view }}"
        extattrs:
          Contacts: "{{ request_requestor }}"
          Description: "{{ request_description }}"
        comment: "{{ request_comment }}"
        state: present
        container: yes
        provider: "{{ nios_provider }}"
      delegate_to: localhost
      tags: [never, setup]
