# code: language=Ansible insertSpaces=true tabSize=2

- name: Create IP
  hosts: nios
  connection: local
  tasks:

    - name: Assert arguments
      assert:
        that: "{{ item.test }}"
        fail_msg: "Rejected requested {{ item.name }}: '{{ item.data }}'"
        success_msg: "Accepted requested {{ item.name }}: '{{ item.data }}'"
      with_items:
        - name: "network view"
          data: "{{ request_view | default('') }}"
          test:
            - "item.data | length > 0"
        - name: "network container"
          data: "{{ request_container | default('') }}"
          test:
            - "item.data | length > 0"
        - name: "network"
          data: "{{ request_network | default('') }}"
          test:
            - "item.data | length > 0"
        - name: "DNS zone"
          data: "{{ request_zone | default('') }}"
          test:
            - "item.data | length > 0"
        - name: "IP count"
          data: "{{ request_count | default(-1) | int }}"
          test:
            - "item.data | int > 0 and item.data | int <= 245"
        - name: "name template"
          data: !unsafe "{{ request_name }}" 
          test:
            - "item.data | length > 0"

      tags: [always]
    
    - name: Lookup view, container and network
      set_fact:
        infoblox_view: "{{ lookup('nios', 'view', provider=nios_provider, filter={'name': request_view}) }}"
        infoblox_container: "{{ lookup('nios', 'networkcontainer', extattrs={'Plateforme': request_container}, provider=nios_provider) }}"
        infoblox_network: "{{ lookup('nios', 'network', provider=nios_provider, filter={'network': request_network}) }}"
      tags: [always]

    - name: Assert view, container and network
      assert:
        that:
          - "item.data is mapping and item.data | length > 0"
        fail_msg: "The requested {{ item.kind }} '{{ item.name }}' was not found in Infoblox"
        success_msg: "The requested {{ item.kind }} '{{ item.name }}' is valid"
      with_items:
        - kind: 'network view'
          name: "{{ request_view }}"
          data: "{{ infoblox_view }}"
        - kind: 'network container'
          name: "{{ request_container }}"
          data: "{{ infoblox_container }}"
        - kind: 'network'
          name: "{{ request_network }}"
          data: "{{ infoblox_network }}"
      tags: [always]

    - name: Assert network inclusion in container
      assert:
        that:
          - "{{ infoblox_container.network | network_in_network(infoblox_network.network) }}"
        fail_msg: "The requested network {{ infoblox_network.network }} is not contained in network container {{ infoblox_container.network }}"
        success_msg: "The requested network {{ infoblox_network.network }} is contained in network container {{ infoblox_container.network }}"
      tags: [always]

    - name: Prepare records
      set_fact:
        request_records: "{{ request_records | default([]) + [{
            'ipv4': record,
            'name': request_name,
            'zone': request_zone,
            'view': request_view,
            'network': request_network
          }] }}"
      loop: "{{ lookup('nios_next_ip', request_network, num=request_count, provider=nios_provider) }}"
      loop_control:
        loop_var: record
        index_var: count
      tags: [never, prepare]

    - name: Set stats
      set_stats:
        data:
          request_records: "{{ request_records }}"
      tags: [never, prepare]

    # - name: Create records
    #   debug:
    #     msg: "Would create record {{ record.name }}.{{ record.zone }} at {{ record.ipv4 }} on view {{ record.view }} in network {{ record.network }}"
    #   loop: "{{ request_records }}"
    #   loop_control:
    #     loop_var: record
    #     index_var: count
    #   tags: [never, setup, debug]

    - name: Create records
      community.general.nios_host_record:
        name: "{{ record.name }}.{{ record.zone }}"
        view: "{{ record.view }}"
        ipv4addrs:
          - ipv4addr: "{{ record.ipv4 }}"
        comment: "Created by the IPAM automation project"
        state: present
        provider: "{{ nios_provider }}"
      loop: "{{ request_records }}"
      loop_control:
        loop_var: record
        index_var: count
      tags: [never, setup, create]


- name: Register host records
  hosts: device42
  tasks:

    # - name: Register host records
    #   debug:
    #     msg: "Would register record {{ record.name }}.{{ record.zone }} at {{ record.ipv4 }} on view {{ record.view }} in network {{ record.network }}"
    #   loop: "{{ hostvars[groups['nios'][0]]['request_records'] }}"
    #   loop_control:
    #     loop_var: record
    #     index_var: count
    #   tags: [never, setup, register]

    - name: Register host records
      device42_api:
        meth: POST
        path: api/1.0/ips
        data:
          ipaddress: "{{ record.ipv4 }}"
          subnet: "{{ record.network }}"
      loop: "{{ hostvars[groups['nios'][0]]['request_records'] }}"
      loop_control:
        loop_var: record
        index_var: count
      tags: [never, setup]
