# code: language=Ansible insertSpaces=true tabSize=2

- name: Notify by mail
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Setup arguments
      set_fact:
        # Resource should be set at the workflow level
        notify_resource: "{{ notify_resource | default('Unknown resource') }}"
        # Kind, status and message should be set at the job level
        notify_action: "{{ notify_action | default('Unknown action') }}"
        notify_status: "{{ notify_status | default('Unknwon status') }}"
        notify_message: "{{ notify_message | default('Unknown message') }}"
        # The job ID is deducted automatically
        notify_job_approval_id: "{{ awx_job_id | default(0) | int + 2 }}"
      tags: [always]


    - name: Notify
      mail:
        host: smtp.dt.ept.lu
        port: 25
        subject: "[IPAM] - {{ notify_resource }} {{ notify_action }} - {{ notify_status }}"
        body: "{{ lookup('template', '../templates/mail_notification.html.j2') }}"
        from: ansible@post.lu
        to: ["{{ tower_user_email }}"]
        charset: "utf-8" 
        subtype: "html"
      when:
        - "tower_user_email | default('') | length > 0"
      delegate_to: localhost
      run_once: yes
      tags: [always]
