# code: language=Ansible insertSpaces=true tabSize=2

- name: Tests - Get
  hosts: device42
  tasks:

    - block:

      - name: Get all devices
        device42_api:
          meth: GET
          path: api/2.0/devices
          data:
            limit: 10
        register: _devices

      - debug:
          var: _devices

      - name: Get devices by name
        device42_api:
          meth: GET
          path: api/2.0/devices
          data:
            name: G121-LAN-5820
            foobar: 42
        register: _named_devices

      - debug:
          var: _named_devices

      - name: Get device by ID
        device42_api:
          meth: GET
          path: api/1.0/devices/5127
        register: _device_id

      - debug:
          var: _device_id

      tags: [never, get]


- name: Tests - Post
  hosts: device42
  tasks:

    - block:

      - name: Create subnet
        device42_api:
          meth: POST
          path: api/1.0/subnets
          data:
            network: "172.27.253.128"
            mask_bits: "25"
        register: _subnet
      
      - debug:
          var: _subnet
      
      tags: [never, post]
