# code: language=Ansible insertSpaces=true tabSize=2

- name: Tests - Lookups
  hosts: nios
  collections:
    - infoblox.nios_modules
  connection: local
  tasks:

    - block:

      - name: Return the list of network views
        debug:
          msg: "{{ lookup('community.general.nios', 'networkview', provider=nios_provider) }}"

      - name: Return the list of views
        debug:
          msg: "{{ lookup('community.general.nios', 'view', provider=nios_provider) }}"

      - name: Return a single host record
        debug:
          msg: "{{ lookup('community.general.nios', 'record:host', filter={'name': 'k8s-ict-master-01.dt.ept.lu'}, provider=nios_provider) }}"

      - name: Return next IP
        debug:
          msg: "{{ lookup('infoblox.nios_modules.nios_next_ip', '172.29.42.0/24', provider=nios_provider) }}"

      - name: Return the list of networks
        debug:
          msg: "{{ lookup('infoblox.nios_modules.nios_lookup', 'network', filter={'network_view': 'DT-internal', 'network': '172.29.42.0/24'}, provider=nios_provider) }}"

      - name: Return the list of networks containers
        debug:
          msg: "{{ lookup('infoblox.nios_modules.nios_lookup', 'networkcontainer', extattrs={'Plateforme': '49435400000001'}, provider=nios_provider) }}"

      tags: [never, lookup, lookups]


- name: Tests - Setup (create resources)
  hosts: nios
  collections:
    - infoblox.nios_modules
  connection: local
  tasks:

    - block:

      - name: Create a host record
        infoblox.nios_modules.nios_host_record:
          name: created-by-ansible.dt.ept.lu
          view: DT-internal
          ipv4addrs:
            - ipv4addr: "{{ lookup('infoblox.nios_modules.nios_next_ip', '172.29.42.0/24', provider=nios_provider)[0] }}"
          comment: "Host record created by Ansible test playbook"
          state: present
          provider: "{{ nios_provider }}"
        register: _create_host_record
        failed_when:
          - _create_host_record.failed and not "already exists" in _create_host_record.msg
        delegate_to: localhost
  
      - name: Create a network
        infoblox.nios_modules.nios_network:
          network: 172.27.253.128/25
          network_view: DT-internal
          extattrs:
            Plateforme: "49435400000003"
          comment: "Network created by Ansible test playbook"
          state: present
          provider: "{{ nios_provider }}"
        register: _create_network
        delegate_to: localhost

      tags: [never, setup]


- name: Tests - Teardown & remove (delete resources)
  hosts: nios
  collections:
    - infoblox.nios_modules
  connection: local
  tasks:

    - block:

      - name: Delete a host record
        infoblox.nios_modules.nios_host_record:
          name: created-by-ansible.dt.ept.lu
          view: "DT-internal"
          state: absent
          provider: "{{ nios_provider }}"
        delegate_to: localhost
      
      - name: Delete a network
        infoblox.nios_modules.nios_network:
          network: 172.27.253.128/25
          network_view: DT-internal
          state: absent
          provider: "{{ nios_provider }}"
        delegate_to: localhost
      
      tags: [never, teardown, remove]
